version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alpha_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672" # Porta AMQP
      - "15672:15672" # Painel web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  alpha:
    image: ruanfonseca2023/alpha:d9aa464a66d96f618865b38c896616a5a83c4774
    container_name: alpha
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alpha_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq

  consumer:
    image: ruanfonseca2023/consumer:latest
    container_name: consumer
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 9191
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alpha_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "9191:9191"
    depends_on:
      - alpha

volumes:
  rabbitmq_data:
  mysql_data:
