version: "3.8"

services:
  alpha:
    image: ruanfonseca2023/alpha:latest
    container_name: alpha
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 8080
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  consumer:
    image: ruanfonseca2023/consumer:latest
    container_name: consumer
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 9191
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "9191:9191"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Painel web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
