version: "3.8"

services:
  alpha:
    image: ruanfonseca2023/alpha:latest
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 8080
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "8080:8080" # Render vai expor publicamente
    depends_on:
      - rabbitmq
    restart: always

  consumer:
    image: ruanfonseca2023/consumer:latest
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 9191
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    # NÃ£o expor portas publicamente no Render
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
