version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: alpha_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  alpha:
    image: ruanfonseca2023/alpha:latest
    container_name: alpha
    restart: always
    pull_policy: always
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alpha_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  consumer:
    image: ruanfonseca2023/consumer:latest
    container_name: consumer
    restart: always
    pull_policy: always
    environment:
      JAVA_OPTS: ""
      SERVER_PORT: 9191
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/alpha_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: 123456
    ports:
      - "9191:9191"
    depends_on:
      - alpha

  # FRONTEND (Servicepro-Front) + NGINX
  servicepro-front:
    image: ruanfonseca2023/servicepro-front:latest
    container_name: servicepro-front
    pull_policy: always
    volumes:
      - servicepro_front_build:/usr/share/nginx/html
    command:
      [
        "/bin/sh",
        "-c",
        "rm -rf /usr/share/nginx/html/* && cp -r /app/dist/* /usr/share/nginx/html",
      ]

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8085:80"
    volumes:
      - servicepro_front_build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - servicepro-front

volumes:
  rabbitmq_data:
  mysql_data:
  servicepro_front_build:
